feat(shader): add shader module and resource
Orillusion/orillusion pull request #24
Opened 2023-04-23 10:36 UTC by SirXuNian

add inline shader
add uniform shader
add matrix shader
add cluster shader
add shadow shader
add normalMap shader
add brdf shader
add lighting function shader
add light uniform shader
add lit material shader
add unlit material shader
add material color shader
add gbuffer shader
add skyGbuffer shader
add castShader

2023-04-23 10:55 UTC, hellmor approved these changes

2023-04-23 14:38 UTC, Codeboy-cn approved these changes

2023-04-24 04:16 UTC, Codeboy-cn commented on src/engine/assets/shader/lighting/Irradiance_frag.wgsl
> +        //边缘渐渐淡出的系数
Please use english or remove it.

2023-04-24 04:20 UTC, Codeboy-cn requested changes
Please modify the file Irradiance frag.wgsl:59

2023-04-24 05:59 UTC, Codeboy-cn approved these changes

2023-04-24 06:00 UTC, merged